export type StoryboardLocale = "en" | "fa";

export const storyboardCopy = {
  en: {
    back: "Workspace", eyebrow: "Ailoom · Video planning", title: "Shape the story, shot by shot.",
    description: "Keep your scenes, prompts and references in one private storyboard. Arrange the sequence before you generate or assemble the film.",
    private: "Private workspace", boardLabel: "Storyboards", newBoard: "New storyboard",
    boardName: "Storyboard name", createBoard: "Create storyboard", creating: "Creating…",
    selectBoard: "Select a storyboard", noBoards: "A clear story starts with a frame.",
    noBoardsDescription: "Create a storyboard to map the sequence, then add a shot for every moment you want to make.",
    boardDetails: "Storyboard details", descriptionLabel: "Description", saveBoard: "Save details",
    deleteBoard: "Delete storyboard", deleteBoardConfirm: "Delete this storyboard and all its shot plans? Your media files remain in the library.",
    shots: "Shot sequence", shotCount: "shots", addShot: "Add shot", noShots: "No shots in this sequence yet.",
    noShotsDescription: "Add an opening shot, then build the pacing from there.",
    edit: "Edit", moveEarlier: "Move earlier", moveLater: "Move later", deleteShot: "Delete shot",
    deleteShotConfirm: "Delete this shot plan? Attached media files remain in the library.",
    shotEditor: "Shot details", newShot: "New shot", editShot: "Edit shot", closeEditor: "Close editor",
    shotTitle: "Shot title", prompt: "Direction & prompt", promptHint: "Describe the action, camera movement, lighting and ending frame.",
    model: "Planned model", duration: "Duration", seconds: "seconds", aspect: "Frame ratio",
    firstFrame: "First frame", lastFrame: "Last frame", references: "References", output: "Chosen clip",
    none: "None selected", selectReference: "Choose existing media", library: "Your private library",
    upload: "Upload media", uploading: "Uploading…", loadMore: "Load more media", loading: "Loading…",
    refresh: "Refresh", mediaSearch: "Find a file", sourceUpload: "Upload", sourceGeneration: "Generated",
    image: "Image", video: "Video", audio: "Audio", noMedia: "No matching media yet.",
    saveShot: "Save shot", saving: "Saving…", cancel: "Cancel", openClip: "Open selected clip",
    planOnly: "This page saves shot plans and media links. Generate clips in Video Studio, then render the chosen clips here.",
    clipReady: "Clip chosen", renderTitle: "Final assembly", renderMissing: "Choose a video clip for every shot before rendering.",
    renderReady: "Every shot has a chosen clip. The final film will follow the order above.",
    renderButton: "Render film", renderQueued: "The render is queued.", renderStatus: "Render status",
    renderDownload: "Download final film", renderFailed: "The render failed. Check the clips and try again.",
    job_queued: "Queued", job_submitting: "Starting", job_running: "Rendering", job_succeeded: "Ready",
    job_failed: "Failed", job_cancelled: "Cancelled",
    selected: "selected", maxShots: "Up to 64 shots per storyboard · 50 references per shot",
    theme: "Switch theme", language: "Choose language", signedIn: "Signed in as",
    signIn: "Sign in to plan a film", signInDescription: "Storyboards belong to your private Ailoom account.",
    signInAction: "Open Ailoom", failed: "Something went wrong. Please try again.",
    boardSaved: "Storyboard saved.", shotSaved: "Shot saved.", boardDeleted: "Storyboard deleted.",
    shotDeleted: "Shot deleted.", reordered: "Shot order updated.", uploaded: "Media added to your library.",
    titleRequired: "Add a title.", promptRequired: "Add a direction for this shot.",
    modelRequired: "Choose a model.", fileTooLarge: "Choose a file smaller than 100 MB.",
    noModels: "Video models are unavailable right now.", noBoard: "Choose a storyboard to continue."
  },
  fa: {
    back: "فضای کار", eyebrow: "Ailoom · برنامه‌ریزی ویدیو", title: "داستان را نما به نما بساز.",
    description: "صحنه‌ها، پرامپت‌ها و فایل‌های مرجع را در یک استوری‌بورد خصوصی نگه دار و ترتیبشان را مشخص کن.",
    private: "فضای خصوصی", boardLabel: "استوری‌بوردها", newBoard: "استوری‌بورد جدید",
    boardName: "نام استوری‌بورد", createBoard: "ساخت استوری‌بورد", creating: "در حال ساخت…",
    selectBoard: "یک استوری‌بورد انتخاب کن", noBoards: "هر داستانی از یک نما شروع می‌شود.",
    noBoardsDescription: "اول استوری‌بورد را بساز و بعد برای هر بخش داستان یک نما اضافه کن.",
    boardDetails: "جزئیات استوری‌بورد", descriptionLabel: "توضیح", saveBoard: "ذخیرهٔ جزئیات",
    deleteBoard: "حذف استوری‌بورد", deleteBoardConfirm: "این استوری‌بورد و تمام طرح‌های نماهایش حذف شود؟ فایل‌های رسانه‌ای در کتابخانه می‌مانند.",
    shots: "ترتیب نماها", shotCount: "نما", addShot: "افزودن نما", noShots: "هنوز نمایی در این توالی نیست.",
    noShotsDescription: "نمای آغازین را اضافه کن و بعد ریتم داستان را بساز.",
    edit: "ویرایش", moveEarlier: "انتقال به قبل", moveLater: "انتقال به بعد", deleteShot: "حذف نما",
    deleteShotConfirm: "طرح این نما حذف شود؟ فایل‌های متصل در کتابخانه می‌مانند.",
    shotEditor: "جزئیات نما", newShot: "نمای جدید", editShot: "ویرایش نما", closeEditor: "بستن ویرایشگر",
    shotTitle: "عنوان نما", prompt: "دستور کار و پرامپت", promptHint: "حرکت، زاویهٔ دوربین، نور و پایان نما را توضیح بده.",
    model: "مدل برنامه‌ریزی‌شده", duration: "مدت", seconds: "ثانیه", aspect: "نسبت تصویر",
    firstFrame: "فریم اول", lastFrame: "فریم آخر", references: "مرجع‌ها", output: "کلیپ انتخاب‌شده",
    none: "انتخاب نشده", selectReference: "انتخاب رسانهٔ موجود", library: "کتابخانهٔ خصوصی شما",
    upload: "بارگذاری رسانه", uploading: "در حال بارگذاری…", loadMore: "رسانه‌های بیشتر", loading: "در حال بارگذاری…",
    refresh: "تازه‌سازی", mediaSearch: "جستجوی فایل", sourceUpload: "بارگذاری‌شده", sourceGeneration: "تولیدشده",
    image: "تصویر", video: "ویدیو", audio: "صدا", noMedia: "رسانهٔ مرتبطی پیدا نشد.",
    saveShot: "ذخیرهٔ نما", saving: "در حال ذخیره…", cancel: "انصراف", openClip: "بازکردن کلیپ انتخاب‌شده",
    planOnly: "این صفحه طرح نماها و پیوند فایل‌ها را ذخیره می‌کند. کلیپ‌ها را در استودیوی ویدیو بساز و کلیپ‌های انتخاب‌شده را همین‌جا مونتاژ کن.",
    clipReady: "کلیپ انتخاب شد", renderTitle: "مونتاژ نهایی", renderMissing: "قبل از رندر، برای همهٔ نماها یک کلیپ ویدیویی انتخاب کن.",
    renderReady: "همهٔ نماها کلیپ دارند. فیلم نهایی از ترتیب بالا پیروی می‌کند.",
    renderButton: "رندر فیلم", renderQueued: "رندر در صف قرار گرفت.", renderStatus: "وضعیت رندر",
    renderDownload: "دریافت فیلم نهایی", renderFailed: "رندر ناموفق بود. کلیپ‌ها را بررسی کن و دوباره تلاش کن.",
    job_queued: "در صف", job_submitting: "در حال شروع", job_running: "در حال رندر", job_succeeded: "آماده",
    job_failed: "ناموفق", job_cancelled: "لغوشده",
    selected: "انتخاب‌شده", maxShots: "حداکثر ۶۴ نما در هر استوری‌بورد · ۵۰ مرجع برای هر نما",
    theme: "تغییر ظاهر", language: "انتخاب زبان", signedIn: "ورود با",
    signIn: "برای برنامه‌ریزی فیلم وارد شو", signInDescription: "استوری‌بوردها به حساب خصوصی Ailoom تو تعلق دارند.",
    signInAction: "بازکردن Ailoom", failed: "خطایی رخ داد. دوباره تلاش کن.",
    boardSaved: "استوری‌بورد ذخیره شد.", shotSaved: "نما ذخیره شد.", boardDeleted: "استوری‌بورد حذف شد.",
    shotDeleted: "نما حذف شد.", reordered: "ترتیب نماها به‌روز شد.", uploaded: "رسانه به کتابخانه اضافه شد.",
    titleRequired: "یک عنوان بنویس.", promptRequired: "دستور کار این نما را بنویس.",
    modelRequired: "یک مدل انتخاب کن.", fileTooLarge: "فایلی کوچک‌تر از ۱۰۰ مگابایت انتخاب کن.",
    noModels: "مدل‌های ویدیویی فعلاً در دسترس نیستند.", noBoard: "برای ادامه یک استوری‌بورد انتخاب کن."
  }
} satisfies Record<StoryboardLocale, Record<string, string>>;
