export type Locale = "en" | "fa";
export type Theme = "light" | "dark";
export type View = "chat" | "image" | "video" | "audio" | "explore" | "specialists";
export type MediaView = "image" | "video" | "audio";

export const views: View[] = ["chat", "image", "video", "audio", "explore", "specialists"];
export const mediaViews: MediaView[] = ["image", "video", "audio"];

export const modelOptions: Record<View, { id: string; label: string }[]> = {
  chat: [
    { id: "openrouter/auto", label: "Smart choice" }
  ],
  image: [
    { id: "fal-ai/flux-2-pro", label: "FLUX.2 Pro" },
    { id: "nano-banana-2", label: "Nano Banana 2" },
    { id: "wavespeed-ai/z-image/turbo", label: "Z Image Turbo" },
    { id: "fal-ai/qwen-image-edit", label: "Qwen Image Edit" },
    { id: "wavespeed-ai/z-image/turbo-inpaint", label: "Z Image Turbo Inpaint" },
    { id: "fal-ai/ideogram/character", label: "Ideogram Character" },
    { id: "topaz/upscale/image/precision", label: "Topaz Precision Upscale" }
  ],
  video: [
    { id: "fal-ai/veo3.1/fast", label: "Veo 3.1 Fast" },
    { id: "fal-ai/veo3.1/fast/image-to-video", label: "Veo 3.1 Fast · Image to Video" },
    { id: "fal-ai/veo3.1/fast/first-last-frame-to-video", label: "Veo 3.1 Fast · First and Last Frame" },
    { id: "bytedance/seedance-2.5/text-to-video", label: "Seedance 2.5 · Text to Video" },
    { id: "bytedance/seedance-2.5/reference-to-video", label: "Seedance 2.5 · Reference to Video" },
    { id: "fal-ai/ltx-2.3-quality/inpaint", label: "LTX 2.3 Video Inpaint" }
  ],
  audio: [
    { id: "fal-ai/elevenlabs/tts/eleven-v3", label: "ElevenLabs v3" },
    { id: "elevenlabs/music/v2", label: "ElevenLabs Music v2" },
    { id: "fal-ai/stable-audio-3/small/music/text-to-audio", label: "Stable Audio 3 Small Music" }
  ],
  explore: [{ id: "auto", label: "Smart choice" }],
  specialists: [{ id: "auto", label: "Smart choice" }]
};

export const workflowCatalog = [
  { id: "product", view: "image" as View, icon: "image", en: "Product image", fa: "تصویر محصول", enDescription: "From source photo to campaign-ready variants.", faDescription: "از عکس اولیه تا نسخه‌های مناسب کمپین.", enPrompt: "Create a clean product image for ", faPrompt: "برای این محصول یک تصویر تمیز بساز: ", steps: 3 },
  { id: "portrait", view: "image" as View, icon: "image", en: "Consistent portrait", fa: "پرترهٔ هماهنگ", enDescription: "Keep one person recognizable across scenes.", faDescription: "چهرهٔ یک نفر را در صحنه‌های مختلف هماهنگ نگه دار.", enPrompt: "Create a portrait with a consistent character: ", faPrompt: "با این شخصیت یک پرترهٔ هماهنگ بساز: ", steps: 4 },
  { id: "short-video", view: "video" as View, icon: "video", en: "Short film", fa: "فیلم کوتاه", enDescription: "Outline shots, references and timing.", faDescription: "نماها، مرجع‌ها و زمان‌بندی را مشخص کن.", enPrompt: "Plan a short film about ", faPrompt: "یک فیلم کوتاه دربارهٔ این موضوع طراحی کن: ", steps: 4 },
  { id: "voiceover", view: "audio" as View, icon: "audio", en: "Voiceover", fa: "گویندگی", enDescription: "Script, language and delivery in one flow.", faDescription: "متن، زبان و شیوهٔ اجرا در یک مسیر.", enPrompt: "Create a voiceover for ", faPrompt: "برای این موضوع گویندگی بساز: ", steps: 3 },
  { id: "social", view: "video" as View, icon: "video", en: "Social clip", fa: "کلیپ شبکهٔ اجتماعی", enDescription: "Turn one idea into a compact visual story.", faDescription: "یک ایده را به داستانی تصویری و کوتاه تبدیل کن.", enPrompt: "Create a short social video about ", faPrompt: "دربارهٔ این موضوع یک ویدیوی کوتاه بساز: ", steps: 4 }
];

export const specialistCatalog = [
  { id: "general", en: "General health", fa: "سلامت عمومی", enDescription: "Understand common health questions and prepare for a clinical visit.", faDescription: "پرسش‌های رایج سلامت را بهتر بفهم و برای مراجعه آماده شو.", enPrompt: "Help me understand this general health question: ", faPrompt: "کمکم کن این پرسش سلامت عمومی را بهتر بفهمم: " },
  { id: "skin", en: "Skin & hair", fa: "پوست و مو", enDescription: "Explore skin and hair topics with clear limits and references.", faDescription: "موضوع‌های پوست و مو را با منابع و محدودیت‌های روشن بررسی کن.", enPrompt: "Help me understand this skin or hair question: ", faPrompt: "کمکم کن این پرسش پوست و مو را بهتر بفهمم: " },
  { id: "mental", en: "Mental well-being", fa: "سلامت روان", enDescription: "Get supportive information and options for seeking professional help.", faDescription: "اطلاعات حمایتی و راه‌های مراجعه به متخصص را پیدا کن.", enPrompt: "Help me understand this mental well-being question: ", faPrompt: "کمکم کن این پرسش سلامت روان را بهتر بفهمم: " }
];

export const copy = {
  en: {
    nav: { chat: "Chat", image: "Image", video: "Video", audio: "Audio", explore: "Explore", specialists: "Specialists" },
    welcome: "Ailoom workspace",
    signIn: "Sign in",
    admin: "Admin",
    changeTheme: "Switch theme",
    chooseLanguage: "Choose language",
    privateWorkspace: "A private workspace, open by invitation.",
    menu: "Primary navigation",
    home: "Ailoom home",
    chatHeadingFirst: "It starts with",
    chatHeadingSecond: "a question.",
    chatDescription: "Speak naturally. Choose your model. Make images, video and sound without losing your train of thought.",
    newConversation: "Start a conversation",
    ideaBegins: "Your idea begins here",
    chatPlaceholder: "Ask anything, or describe what you’d like to make…",
    attach: "Attach a file",
    model: "Model",
    smartChoice: "Smart choice",
    send: "Send",
    chatImageMode: "Image",
    chatImageModeHint: "Create an image in this conversation",
    chatTextModeHint: "Return to text chat",
    chatImagePlaceholder: "Describe the image you want to create…",
    searchModels: "Search models by name or ID",
    noModelsFound: "No matching models.",
    webSearch: "Web",
    webSearchHint: "Search the web with sources",
    webSearchNoImage: "Remove the attachment before searching the web.",
    startTyping: "Start typing now. You’ll sign in when you’re ready to send.",
    starterLabel: "Try a starting point",
    starters: [
      { label: "Think through an idea", prompt: "Help me think through an idea: ", view: "chat" as View },
      { label: "Make an image", prompt: "Create an image of ", view: "image" as View },
      { label: "Plan a short video", prompt: "Plan a short video about ", view: "video" as View }
    ],
    fromThought: "From first thought to finished work.",
    madeForProcess: "Made for the whole process",
    wholeProcess: "Choose the space that fits the work. The conversation can always keep going.",
    capabilityDescription: {
      chat: "Think, write and solve together.",
      image: "Make a visual, then make it yours.",
      video: "Shape a scene from first frame to last.",
      audio: "Turn written text into natural speech.",
      explore: "Discover a starting point for your work.",
      specialists: "Focused help on important topics."
    },
    interfacePreview: "The interface is ready for its service connections.",
    draftSaved: "Your draft stays on this device.",
    loginTitle: "Continue with Ailoom",
    loginDescription: "Sign in to continue. What you wrote is saved, so you can pick up right where you left off.",
    email: "Email",
    password: "Password",
    name: "Name",
    createAccount: "Create account",
    existingAccount: "Already have an account? Sign in",
    useInvitation: "Have an invitation? Create your account",
    invitationOnly: "A valid invitation is required to create an account.",
    invitationReady: "Your invitation is ready. Create an account or sign in.",
    authWorking: "Please wait…",
    signOut: "Sign out",
    exportAccount: "Export account data (JSON; media files download separately)",
    signedInAs: "Signed in as",
    conversationHistory: "Conversations",
    dubbingTool: "Dubbing studio",
    effectsTool: "Sound effects",
    newChat: "New chat",
    noConversations: "Your conversations will appear here.",
    loadingConversations: "Loading conversations…",
    loadingWorkflows: "Loading workflows…",
    loadingMessages: "Loading conversation…",
    sendError: "Your message could not be sent. Your draft is still here.",
    retry: "Try again",
    noMessages: "Start with a thought. Your conversation will appear here.",
    attachmentUnavailable: "File upload is being connected. Remove the attachment to send text now.",
    chatImageOnly: "Chat accepts one PNG, JPEG or WebP image under 10 MB.",
    chatAttachmentUnsupported: "Chat accepts one PNG, JPEG, WebP or PDF file under 10 MB.",
    authError: "Could not sign in. Please check your details and try again.",
    sessionError: "Your session could not be checked. Try reloading this page.",
    modelLoading: "Loading models…",
    modelUnavailable: "Model catalog is unavailable. Smart choice remains available.",
    savedDraft: "Your saved draft",
    continueSignIn: "Continue to sign in",
    keepEditing: "Keep editing",
    signInPending: "Sign-in is being connected to this workspace.",
    uploadPending: "File processing is being connected. Your local preview stays on this device.",
    close: "Close",
    scrollPreview: "Explore the interface",
    outputTitle: "One conversation, many kinds of output.",
    outputEyebrow: "Conversation canvas",
    outputDescription: "Keep text, files and generated media together in the same thread.",
    outputTabs: { text: "Text & sources", image: "Image", video: "Video", audio: "Audio" },
    sampleOnly: "Layout preview",
    samplePrompt: "Help me turn this idea into something I can share.",
    sampleText: "A response can combine a clear answer, useful steps and links to its sources. Generated work stays attached to the conversation.",
    sourceLabel: "Source slots",
    outputPlaceholder: "Generated output will appear here",
    imageOutput: "Image output",
    videoOutput: "Video output",
    audioOutput: "Audio output",
    exportReady: "Open, download and sharing controls appear beside each result.",
    studioEyebrow: "Creative workspace",
    layersTool: "Layered image editor",
    loraTool: "Train a private LoRA",
    storyboardTool: "Storyboard & shot timeline",
    captionsTool: "Burn video captions",
    voicesTool: "Personal voices",
    studioTitle: { image: "Image Studio", video: "Video Studio", audio: "Audio Studio" },
    studioDescription: {
      image: "Create, edit and refine imagery with the model and references you choose.",
      video: "Generate a shot, animate reference images or repair a selected interval in an existing clip.",
      audio: "Create speech or music from text, or transcribe an audio or video file."
    },
    studioTab: { image: ["Create", "Edit", "Upscale", "Inpaint", "Character"], video: ["Create", "Reference image", "Repair section", "First + last frame"], audio: ["Speech", "Music", "Transcribe"] },
    canvas: "Canvas",
    canvasReady: "Your canvas is ready",
    addReference: "Describe what you want to make to begin.",
    referenceHint: "Choose a source file, then describe the change you want.",
    dropFile: "Choose a file for a local preview",
    removeFile: "Remove file",
    input: "Input",
    prompt: "Prompt",
    promptByView: {
      image: "Describe the image, edits or detail you want…",
      video: "Describe the shot, movement or change you want…",
      audio: "Write the words you want spoken…"
    },
    settings: "Settings",
    aspectRatio: "Aspect ratio",
    quality: "Quality",
    standard: "Standard",
    high: "High",
    language: "Language",
    automatic: "Automatic",
    english: "English",
    persian: "Persian",
    duration: "Duration",
    seconds: "seconds",
    startTime: "Start",
    endTime: "End",
    repairRange: "Repair selected range",
    repairHint: "Only the selected interval is prepared for regeneration. The final cost depends on the chosen model.",
    noClip: "Add a video to preview and set a repair interval.",
    localPreview: "Local preview",
    generate: "Generate",
    imageModeHint: "The source image is used for this edit. The generated result appears here.",
    inpaintHint: "Brush over only the area to replace. Marked areas are edited; the rest stays protected. Your image and mask are sent to WaveSpeed when you click Generate.",
    inpaintBrush: "Brush size",
    inpaintClear: "Clear mask",
    inpaintMissing: "Paint the area to change before generating.",
    inpaintInvalid: "Choose a PNG or JPEG image from 256 to 4096 pixels, up to 16 MP and 8 MB.",
    inpaintCost: "Published provider price: about $0.02 per image; your account charge may differ.",
    characterHint: "Use one clear character portrait as a reference, then describe a new scene. After you click Generate, the private image is sent to fal. Facial similarity can vary across outputs.",
    characterInvalid: "Choose one PNG, JPEG or WebP image up to 10 MB.",
    characterCost: "Published fal price: $0.15 per BALANCED image or $0.20 per QUALITY image. Your account charge may differ.",
    upscaleDescription: "Choose an image to enlarge with Topaz. No prompt is needed.",
    upscaleModeHint: "The original image is sent to Topaz after you click Upscale. The result appears here and in your private outputs.",
    upscaleFactor: "Scale",
    upscalePreset: "Enhancement model",
    upscaleFormat: "Output format",
    upscaleAction: "Upscale image",
    upscaleUnsupportedFile: "Choose a PNG, JPEG or WebP image.",
    videoModeHint: "The uploaded clip stays local in this interface preview.",
    firstFrame: "First frame",
    lastFrame: "Last frame",
    chooseFirstFrame: "Choose first frame",
    chooseLastFrame: "Choose last frame",
    firstLastHint: "Choose the opening and ending images. Describe the motion between them; both images are sent to Veo after you click Generate.",
    firstLastMissing: "Choose both a first and last image before generating.",
    firstLastTooLarge: "Each frame must be a PNG, JPEG or WebP image under 8 MB.",
    audioModeHint: "Choose a language when the model supports it.",
    audioCanvasHint: "Enter the words you want spoken, then choose a language and generate speech.",
    musicPrompt: "Describe the genre, mood, instruments, tempo and any lyrics or vocal language…",
    musicCanvasHint: "Describe the music you want, choose a model and duration, then generate.",
    musicModeHint: "Your prompt is sent to the selected music model. Mention the vocal language in the prompt when needed.",
    musicInstrumental: "Instrumental only",
    musicElevenCost: "Fal lists $0.60 per started output minute for ElevenLabs Music v2. The displayed amount is an estimate.",
    musicStableCost: "Stable Audio 3 Small Music cost depends on the request and account.",
    transcriptionTitle: "Transcribe audio or video",
    transcriptionDescription: "Choose an MP3, WAV, OGG, M4A, MP4 or WebM file up to 50 MB.",
    transcriptionChooseFile: "Choose audio or video",
    transcriptionNoFile: "Choose a file before transcribing.",
    transcriptionTooLarge: "Choose a file smaller than 50 MB.",
    transcriptionDiarize: "Identify speakers",
    transcriptionProviderNote: "When you click Transcribe, this file is sent to ElevenLabs. Ailoom does not save the file or transcript.",
    transcriptionAction: "Transcribe",
    transcriptionWorking: "Transcribing…",
    transcriptionResult: "Transcript",
    transcriptionEmpty: "No speech was detected in this file.",
    transcriptionDetectedLanguage: "Detected language",
    transcriptionCopy: "Copy text",
    transcriptionCopied: "Copied",
    transcriptionCopyError: "Could not copy the transcript.",
    transcriptionDownload: "Download .txt",
    transcriptionInvalidResponse: "The transcript response could not be read.",
    transcriptionSpeaker: "Speaker",
    videoAudio: "Generate audio",
    automaticDuration: "Auto",
    exploreEyebrow: "Explore",
    exploreTitle: "A good place to begin.",
    exploreDescription: "Start with a workflow, then change the steps to fit your project.",
    stepCount: "steps",
    useWorkflow: "Use workflow",
    createWorkflow: "Create a workflow",
    specialistEyebrow: "Specialists",
    specialistTitle: "Focused questions deserve careful answers.",
    specialistDescription: "Choose a topic and bring your question into a source-aware conversation.",
    specialistNotice: "AI health information can help you prepare questions, but it cannot diagnose, prescribe or replace a qualified clinician. For urgent danger, contact local emergency services.",
    askSpecialist: "Ask about this topic",
    inviteRequired: "Access is by invitation.",
    noGeneration: "This screen is an interface scaffold. No model request is sent yet.",
    generationQueued: "Generation queued",
    generationRunning: "Generating",
    generationDone: "Generation complete",
    generationFailed: "Generation failed",
    generationCancelled: "Generation cancelled",
    generationOutputMissing: "The task completed, but no output was returned.",
    generationHint: "You can leave this page; the job keeps running.",
    generationNotReady: "Choose a supported model before generating.",
    unsupportedOperation: "This operation needs a reference workflow before it can run.",
    openResult: "Open result",
    assetPrivate: "Private",
    assetPublic: "Public",
    assetVisibilityLoading: "Checking access…",
    assetVisibilityUnavailable: "Access unavailable",
    makePrivate: "Make private",
    makePublic: "Make public",
    assetVisibilitySaving: "Saving…",
    assetVisibilityError: "Could not update access to this result.",
    downloadResult: "Download",
    mediaLibraryEyebrow: "Your creations",
    mediaLibraryTitle: "Recent outputs",
    mediaLibraryDescription: "Open a previous creation or download the original file.",
    mediaLibraryRefresh: "Refresh",
    mediaLibraryLoading: "Loading your creations…",
    mediaLibraryEmpty: "Your generated outputs will appear here.",
    mediaLibraryError: "Could not load your creations.",
    mediaLibraryBack: "Back to current work",
    mediaLibraryLoadMore: "Load more",
    mediaLibraryLoadingMore: "Loading more…",
    priceEstimate: "Estimated provider cost",
    noPriceEstimate: "Live price depends on the provider.",
    exploreEmpty: "No published workflows yet. Create your first private workflow.",
    exploreLoadError: "Workflows could not be loaded. Try again shortly.",
    specialistLoadError: "Specialists could not be loaded. Try again shortly.",
    specialistEmpty: "No specialists are available yet.",
    workflowTitle: "Workflow name",
    workflowDescription: "Description",
    workflowCategory: "Category",
    workflowSteps: "Steps",
    workflowInputs: "Inputs",
    workflowInputKey: "Placeholder key",
    workflowInputLabel: "Field label",
    workflowInputType: "Field type",
    workflowInputRequired: "Required",
    workflowAddInput: "Add input",
    workflowRemoveInput: "Remove input",
    workflowFillInputs: "Fill in the workflow inputs",
    workflowRequired: "Fill in all required fields before continuing.",
    workflowUndefinedInput: "This step contains an undefined placeholder. Edit the template before continuing.",
    workflowReferenceRequired: "Choose a reference file for this step.",
    workflowUnsupportedFile: "This step cannot use the selected file type yet.",
    workflowOneReference: "This step currently supports one reference file.",
    workflowDuplicateInput: "Each placeholder key must be unique.",
    workflowStepTitle: "Step name",
    workflowStepKind: "Output",
    workflowStepModel: "Suggested model",
    workflowStepPrompt: "Prompt for this step",
    workflowAddStep: "Add step",
    workflowRemoveStep: "Remove step",
    workflowSave: "Save workflow",
    workflowCancel: "Cancel",
    workflowEdit: "Edit workflow",
    workflowPrivate: "Private",
    workflowPublic: "Public",
    workflowPublish: "Publish",
    workflowUnpublish: "Make private",
    workflowOwn: "Your workflow",
    workflowSaving: "Saving…",
    workflowChooseStep: "Choose a step to continue",
    workflowUseStep: "Use this step",
    workflowError: "Could not save this workflow.",
    workflowTitlePlaceholder: "e.g. Product launch visual",
    workflowDescriptionPlaceholder: "What does this workflow help create?",
    workflowCategoryPlaceholder: "e.g. Marketing",
    workflowPromptPlaceholder: "Describe what this step should produce…",
    workflowStepPlaceholder: "e.g. Draft concept",
    sourceLinks: "Reference sources"
  },
  fa: {
    nav: { chat: "گفتگو", image: "تصویر", video: "ویدیو", audio: "صدا", explore: "کاوش", specialists: "متخصصان" },
    welcome: "فضای کار Ailoom",
    signIn: "ورود",
    admin: "مدیریت",
    changeTheme: "تغییر پوسته",
    chooseLanguage: "انتخاب زبان",
    privateWorkspace: "فضای کاری خصوصی، با دسترسی از طریق دعوت.",
    menu: "پیمایش اصلی",
    home: "صفحهٔ اصلی Ailoom",
    chatHeadingFirst: "همه‌چیز با",
    chatHeadingSecond: "یک سؤال شروع می‌شود.",
    chatDescription: "راحت گفتگو کن، مدل را انتخاب کن و بدون قطع شدن مسیر فکر، تصویر، ویدیو و صدا بساز.",
    newConversation: "یک گفتگو شروع کن",
    ideaBegins: "ایده‌ات از اینجا شروع می‌شود",
    chatPlaceholder: "هر سؤالی داری بپرس یا چیزی را که می‌خواهی بسازی توصیف کن…",
    attach: "افزودن فایل",
    model: "مدل",
    smartChoice: "انتخاب هوشمند",
    send: "ارسال",
    chatImageMode: "تصویر",
    chatImageModeHint: "در همین گفتگو تصویر بساز",
    chatTextModeHint: "بازگشت به گفتگوی متنی",
    chatImagePlaceholder: "تصویری را که می‌خواهی بسازی توصیف کن…",
    searchModels: "جست‌وجوی نام یا شناسهٔ مدل",
    noModelsFound: "مدلی پیدا نشد.",
    webSearch: "وب",
    webSearchHint: "جست‌وجوی وب با منابع",
    webSearchNoImage: "برای جست‌وجوی وب، پیوست را حذف کن.",
    startTyping: "همین حالا بنویس. موقع ارسال می‌توانی وارد شوی.",
    starterLabel: "برای شروع امتحان کن",
    starters: [
      { label: "یک ایده را بررسی کن", prompt: "کمکم کن این ایده را بررسی کنم: ", view: "chat" as View },
      { label: "یک تصویر بساز", prompt: "تصویری بساز از ", view: "image" as View },
      { label: "یک ویدیوی کوتاه طراحی کن", prompt: "برای این موضوع یک ویدیوی کوتاه طراحی کن: ", view: "video" as View }
    ],
    fromThought: "از اولین فکر تا نتیجهٔ نهایی.",
    madeForProcess: "برای تمام مسیر کار",
    wholeProcess: "فضای مناسب کارت را انتخاب کن. گفتگو همیشه می‌تواند ادامه پیدا کند.",
    capabilityDescription: {
      chat: "با هم فکر کن، بنویس و مسئله حل کن.",
      image: "تصویر بساز و آن را دقیق‌تر کن.",
      video: "از اولین فریم تا آخرین نما.",
      audio: "متن را به گفتار طبیعی تبدیل کن.",
      explore: "برای کارت یک نقطهٔ شروع پیدا کن.",
      specialists: "راهنمایی متمرکز برای موضوع‌های مهم."
    },
    interfacePreview: "رابط برای اتصال به سرویس‌ها آماده است.",
    draftSaved: "پیش‌نویست روی همین دستگاه می‌ماند.",
    loginTitle: "با Ailoom ادامه بده",
    loginDescription: "برای ادامه وارد شو. چیزی که نوشتی ذخیره شده و می‌توانی از همان‌جا ادامه بدهی.",
    email: "ایمیل",
    password: "رمز عبور",
    name: "نام",
    createAccount: "ساخت حساب",
    existingAccount: "حساب داری؟ وارد شو",
    useInvitation: "دعوت‌نامه داری؟ حساب بساز",
    invitationOnly: "برای ساخت حساب، دعوت‌نامهٔ معتبر لازم است.",
    invitationReady: "دعوت‌نامه‌ات آماده است. حساب بساز یا وارد شو.",
    authWorking: "کمی صبر کن…",
    signOut: "خروج",
    exportAccount: "دریافت داده‌های حساب (JSON؛ فایل‌های رسانه‌ای جداگانه دریافت می‌شوند)",
    signedInAs: "وارد شده با",
    conversationHistory: "گفتگوها",
    dubbingTool: "استودیوی دوبله",
    effectsTool: "افکت صوتی",
    newChat: "گفتگوی تازه",
    noConversations: "گفتگوهای تو اینجا نمایش داده می‌شوند.",
    loadingConversations: "در حال بارگذاری گفتگوها…",
    loadingWorkflows: "در حال بارگذاری گردش‌کارها…",
    loadingMessages: "در حال بارگذاری گفتگو…",
    sendError: "پیام ارسال نشد. پیش‌نویس تو هنوز اینجاست.",
    retry: "تلاش دوباره",
    noMessages: "با یک فکر شروع کن. گفتگوی تو اینجا نمایش داده می‌شود.",
    attachmentUnavailable: "افزودن فایل در حال اتصال است. برای ارسال متن، فایل را حذف کن.",
    chatImageOnly: "در گفتگو فقط یک تصویر PNG، JPEG یا WebP کوچک‌تر از ۱۰ مگابایت پذیرفته می‌شود.",
    chatAttachmentUnsupported: "در گفتگو یک فایل PNG، JPEG، WebP یا PDF کوچک‌تر از ۱۰ مگابایت پذیرفته می‌شود.",
    authError: "ورود انجام نشد. اطلاعاتت را بررسی کن و دوباره تلاش کن.",
    sessionError: "نشست کاربری بررسی نشد. صفحه را دوباره بارگذاری کن.",
    modelLoading: "مدل‌ها در حال بارگذاری‌اند…",
    modelUnavailable: "فهرست مدل‌ها در دسترس نیست. انتخاب هوشمند همچنان فعال است.",
    savedDraft: "پیش‌نویس ذخیره‌شده",
    continueSignIn: "ادامه برای ورود",
    keepEditing: "ادامهٔ نوشتن",
    signInPending: "ورود کاربران در حال اتصال به این فضای کار است.",
    uploadPending: "پردازش فایل در حال اتصال است. پیش‌نمایش محلی فقط روی همین دستگاه می‌ماند.",
    close: "بستن",
    scrollPreview: "دیدن رابط",
    outputTitle: "یک گفتگو، خروجی‌های گوناگون.",
    outputEyebrow: "بوم گفتگو",
    outputDescription: "متن، فایل‌ها و رسانه‌های تولیدشده را در همان گفتگو کنار هم نگه دار.",
    outputTabs: { text: "متن و منابع", image: "تصویر", video: "ویدیو", audio: "صدا" },
    sampleOnly: "پیش‌نمایش چیدمان",
    samplePrompt: "کمکم کن این ایده را به چیزی قابل ارائه تبدیل کنم.",
    sampleText: "پاسخ می‌تواند توضیح روشن، گام‌های کاربردی و پیوند منابع را کنار هم بیاورد. خروجی‌های ساخته‌شده به گفتگو متصل می‌مانند.",
    sourceLabel: "جایگاه منابع",
    outputPlaceholder: "خروجی ساخته‌شده اینجا نمایش داده می‌شود",
    imageOutput: "خروجی تصویر",
    videoOutput: "خروجی ویدیو",
    audioOutput: "خروجی صدا",
    exportReady: "کنترل‌های باز کردن، دریافت و دسترسی کنار هر خروجی قرار می‌گیرند.",
    studioEyebrow: "فضای خلق",
    layersTool: "ویرایشگر لایه‌ای تصویر",
    loraTool: "آموزش LoRA خصوصی",
    storyboardTool: "استوری‌بورد و ترتیب نماها",
    captionsTool: "چسباندن زیرنویس به ویدیو",
    voicesTool: "صداهای شخصی",
    studioTitle: { image: "استودیوی تصویر", video: "استودیوی ویدیو", audio: "استودیوی صدا" },
    studioDescription: {
      image: "با مدل و مرجع دلخواهت تصویر بساز، ویرایش کن و بهبود بده.",
      video: "یک نما بساز، تصویرهای مرجع را به حرکت درآور یا بازه‌ای از ویدیوی موجود را ترمیم کن.",
      audio: "از متن گفتار یا موسیقی بساز، یا فایل صوتی و ویدیویی را رونویسی کن."
    },
    studioTab: { image: ["ساخت", "ویرایش", "افزایش وضوح", "ویرایش ناحیه‌ای", "شخصیت ثابت"], video: ["ساخت", "تصویر مرجع", "ترمیم بخش", "فریم اول و آخر"], audio: ["گفتار", "موسیقی", "رونویسی"] },
    canvas: "بوم",
    canvasReady: "بوم تو آماده است",
    addReference: "برای شروع، چیزی را که می‌خواهی بسازی توصیف کن.",
    referenceHint: "فایل مرجع را انتخاب کن و تغییری را که می‌خواهی توصیف کن.",
    dropFile: "برای پیش‌نمایش محلی یک فایل انتخاب کن",
    removeFile: "حذف فایل",
    input: "ورودی",
    prompt: "درخواست",
    promptByView: {
      image: "تصویر، ویرایش یا جزئیات مورد نظرت را توصیف کن…",
      video: "نما، حرکت یا تغییری را که می‌خواهی توصیف کن…",
      audio: "متنی را که می‌خواهی خوانده شود بنویس…"
    },
    settings: "تنظیمات",
    aspectRatio: "نسبت تصویر",
    quality: "کیفیت",
    standard: "استاندارد",
    high: "بالا",
    language: "زبان",
    automatic: "خودکار",
    english: "انگلیسی",
    persian: "فارسی",
    duration: "مدت",
    seconds: "ثانیه",
    startTime: "شروع",
    endTime: "پایان",
    repairRange: "ترمیم بازهٔ انتخاب‌شده",
    repairHint: "فقط بازهٔ انتخاب‌شده برای بازتولید آماده می‌شود. هزینهٔ نهایی به مدل انتخابی بستگی دارد.",
    noClip: "برای پیش‌نمایش و تعیین بازهٔ ترمیم، ویدیو اضافه کن.",
    localPreview: "پیش‌نمایش محلی",
    generate: "تولید",
    imageModeHint: "تصویر مرجع برای همین ویرایش استفاده می‌شود و نتیجه اینجا نمایش داده خواهد شد.",
    inpaintHint: "فقط روی ناحیه‌ای که می‌خواهی عوض شود قلم بکش. بخش‌های علامت‌خورده ویرایش و بقیه حفظ می‌شوند. تصویر و ماسک پس از کلیک روی «تولید» به WaveSpeed فرستاده می‌شوند.",
    inpaintBrush: "اندازهٔ قلم",
    inpaintClear: "پاک کردن ماسک",
    inpaintMissing: "پیش از تولید، ناحیهٔ موردنظر را با قلم مشخص کن.",
    inpaintInvalid: "تصویر PNG یا JPEG با ابعاد ۲۵۶ تا ۴۰۹۶ پیکسل، حداکثر ۱۶ مگاپیکسل و ۸ مگابایت انتخاب کن.",
    inpaintCost: "قیمت منتشرشدهٔ سرویس حدود ۰٫۰۲ دلار برای هر تصویر است؛ هزینهٔ حساب ممکن است فرق کند.",
    characterHint: "یک پرترهٔ واضح از شخصیت را مرجع بده و صحنهٔ تازه را توصیف کن. پس از کلیک روی «تولید»، تصویر خصوصی به fal فرستاده می‌شود. شباهت چهره در خروجی‌ها می‌تواند متفاوت باشد.",
    characterInvalid: "یک تصویر PNG، JPEG یا WebP تا ۱۰ مگابایت انتخاب کن.",
    characterCost: "قیمت منتشرشدهٔ fal برای هر تصویر در حالت BALANCED برابر ۰٫۱۵ دلار و در حالت QUALITY برابر ۰٫۲۰ دلار است. هزینهٔ حساب ممکن است فرق کند.",
    upscaleDescription: "برای افزایش وضوح با Topaz یک تصویر انتخاب کن. نیازی به نوشتن درخواست نیست.",
    upscaleModeHint: "پس از کلیک روی «افزایش وضوح»، تصویر اصلی به Topaz فرستاده می‌شود. نتیجه اینجا و در خروجی‌های خصوصی تو نمایش داده می‌شود.",
    upscaleFactor: "میزان بزرگ‌نمایی",
    upscalePreset: "مدل بهبود",
    upscaleFormat: "قالب خروجی",
    upscaleAction: "افزایش وضوح تصویر",
    upscaleUnsupportedFile: "یک تصویر PNG، JPEG یا WebP انتخاب کن.",
    videoModeHint: "ویدیوی بارگذاری‌شده در این پیش‌نمایش فقط روی دستگاه تو می‌ماند.",
    firstFrame: "فریم اول",
    lastFrame: "فریم آخر",
    chooseFirstFrame: "انتخاب فریم اول",
    chooseLastFrame: "انتخاب فریم آخر",
    firstLastHint: "تصویر آغاز و پایان را انتخاب کن و حرکت میان آن‌ها را توضیح بده. هر دو تصویر پس از کلیک روی «تولید» به Veo فرستاده می‌شوند.",
    firstLastMissing: "پیش از تولید، تصویر فریم اول و آخر را انتخاب کن.",
    firstLastTooLarge: "هر فریم باید تصویر PNG، JPEG یا WebP و کوچک‌تر از ۸ مگابایت باشد.",
    audioModeHint: "وقتی مدل پشتیبانی کند، می‌توانی زبان را انتخاب کنی.",
    audioCanvasHint: "متنی را که می‌خواهی خوانده شود بنویس، زبان را انتخاب کن و گفتار بساز.",
    musicPrompt: "سبک، حال‌وهوا، سازها، ضرب‌آهنگ و در صورت نیاز شعر و زبان خواننده را توصیف کن…",
    musicCanvasHint: "موسیقی دلخواهت را توصیف کن، مدل و مدت را انتخاب کن و بساز.",
    musicModeHint: "درخواستت به مدل موسیقی انتخاب‌شده فرستاده می‌شود. در صورت نیاز زبان خواننده را در درخواست بنویس.",
    musicInstrumental: "فقط بی‌کلام",
    musicElevenCost: "هزینهٔ اعلام‌شدهٔ Fal برای ElevenLabs Music v2 به‌ازای هر دقیقهٔ شروع‌شده ۰٫۶ دلار است. مبلغ نمایش‌داده‌شده برآورد است.",
    musicStableCost: "هزینهٔ Stable Audio 3 Small Music به تنظیمات درخواست و حساب بستگی دارد.",
    transcriptionTitle: "رونویسی صدا یا ویدیو",
    transcriptionDescription: "فایل MP3، WAV، OGG، M4A، MP4 یا WebM تا ۵۰ مگابایت انتخاب کن.",
    transcriptionChooseFile: "انتخاب فایل صوتی یا ویدیویی",
    transcriptionNoFile: "پیش از رونویسی یک فایل انتخاب کن.",
    transcriptionTooLarge: "فایلی کوچک‌تر از ۵۰ مگابایت انتخاب کن.",
    transcriptionDiarize: "تشخیص گویندگان",
    transcriptionProviderNote: "وقتی روی «رونویسی» کلیک کنی، فایل به ElevenLabs فرستاده می‌شود. Ailoom فایل و متن رونویسی را ذخیره نمی‌کند.",
    transcriptionAction: "رونویسی",
    transcriptionWorking: "در حال رونویسی…",
    transcriptionResult: "متن رونویسی",
    transcriptionEmpty: "گفتاری در این فایل شناسایی نشد.",
    transcriptionDetectedLanguage: "زبان شناسایی‌شده",
    transcriptionCopy: "کپی متن",
    transcriptionCopied: "کپی شد",
    transcriptionCopyError: "متن رونویسی کپی نشد.",
    transcriptionDownload: "دریافت فایل متنی",
    transcriptionInvalidResponse: "پاسخ رونویسی خوانده نشد.",
    transcriptionSpeaker: "گوینده",
    videoAudio: "تولید صدا",
    automaticDuration: "خودکار",
    exploreEyebrow: "کاوش",
    exploreTitle: "جایی خوب برای شروع.",
    exploreDescription: "از یک جریان‌کار شروع کن و مرحله‌هایش را برای پروژه‌ات تغییر بده.",
    stepCount: "مرحله",
    useWorkflow: "استفاده از جریان‌کار",
    createWorkflow: "ساخت جریان‌کار",
    specialistEyebrow: "متخصصان",
    specialistTitle: "پرسش‌های دقیق، پاسخ‌های سنجیده.",
    specialistDescription: "موضوع را انتخاب کن و پرسشت را در گفتگویی مبتنی بر منبع مطرح کن.",
    specialistNotice: "اطلاعات سلامت مبتنی بر هوش مصنوعی می‌تواند برای آماده‌کردن سؤال کمک کند، اما تشخیص، نسخه یا جایگزین متخصص نیست. در خطر فوری با اورژانس محل زندگی تماس بگیر.",
    askSpecialist: "پرسش دربارهٔ این موضوع",
    inviteRequired: "دسترسی با دعوت فعال می‌شود.",
    noGeneration: "این صفحه ساختار رابط است و هنوز درخواستی به مدل ارسال نمی‌شود.",
    generationQueued: "در صف تولید",
    generationRunning: "در حال تولید",
    generationDone: "تولید کامل شد",
    generationFailed: "تولید ناموفق بود",
    generationCancelled: "تولید لغو شد",
    generationOutputMissing: "کار کامل شد، اما خروجی دریافت نشد.",
    generationHint: "می‌توانی از این صفحه خارج شوی؛ کار در پس‌زمینه ادامه دارد.",
    generationNotReady: "پیش از تولید یک مدل پشتیبانی‌شده انتخاب کن.",
    unsupportedOperation: "برای اجرای این عملیات، جریان‌کار مرجع لازم است.",
    openResult: "باز کردن خروجی",
    assetPrivate: "خصوصی",
    assetPublic: "عمومی",
    assetVisibilityLoading: "در حال بررسی دسترسی…",
    assetVisibilityUnavailable: "وضعیت دسترسی در دسترس نیست",
    makePrivate: "خصوصی کردن",
    makePublic: "عمومی کردن",
    assetVisibilitySaving: "در حال ذخیره…",
    assetVisibilityError: "دسترسی به این خروجی به‌روزرسانی نشد.",
    downloadResult: "دریافت",
    mediaLibraryEyebrow: "ساخته‌های تو",
    mediaLibraryTitle: "خروجی‌های اخیر",
    mediaLibraryDescription: "خروجی قبلی را باز کن یا فایل اصلی را دریافت کن.",
    mediaLibraryRefresh: "تازه‌سازی",
    mediaLibraryLoading: "در حال بارگذاری خروجی‌ها…",
    mediaLibraryEmpty: "خروجی‌های تولیدشدهٔ تو اینجا نمایش داده می‌شوند.",
    mediaLibraryError: "خروجی‌ها بارگذاری نشدند.",
    mediaLibraryBack: "بازگشت به کار فعلی",
    mediaLibraryLoadMore: "نمایش بیشتر",
    mediaLibraryLoadingMore: "در حال بارگذاری…",
    priceEstimate: "برآورد هزینهٔ ارائه‌دهنده",
    noPriceEstimate: "قیمت نهایی به ارائه‌دهنده بستگی دارد.",
    exploreEmpty: "هنوز جریان‌کار منتشرشده‌ای وجود ندارد. اولین جریان‌کار خصوصی خودت را بساز.",
    exploreLoadError: "جریان‌کارها بارگذاری نشدند. کمی بعد دوباره تلاش کن.",
    specialistLoadError: "متخصصان بارگذاری نشدند. کمی بعد دوباره تلاش کن.",
    specialistEmpty: "هنوز متخصصی در دسترس نیست.",
    workflowTitle: "نام جریان‌کار",
    workflowDescription: "توضیح",
    workflowCategory: "دسته‌بندی",
    workflowSteps: "مرحله‌ها",
    workflowInputs: "ورودی‌ها",
    workflowInputKey: "کلید جای‌گذاری",
    workflowInputLabel: "برچسب فیلد",
    workflowInputType: "نوع فیلد",
    workflowInputRequired: "ضروری",
    workflowAddInput: "افزودن ورودی",
    workflowRemoveInput: "حذف ورودی",
    workflowFillInputs: "ورودی‌های جریان‌کار را تکمیل کن",
    workflowRequired: "پیش از ادامه، فیلدهای ضروری را پر کن.",
    workflowUndefinedInput: "این مرحله یک جای‌گذاری تعریف‌نشده دارد. پیش از ادامه قالب را ویرایش کن.",
    workflowReferenceRequired: "برای این مرحله فایل مرجع انتخاب کن.",
    workflowUnsupportedFile: "این مرحله هنوز از نوع فایل انتخاب‌شده پشتیبانی نمی‌کند.",
    workflowOneReference: "در این مرحله فعلاً تنها یک فایل مرجع پشتیبانی می‌شود.",
    workflowDuplicateInput: "کلیدهای جای‌گذاری باید یکتا باشند.",
    workflowStepTitle: "نام مرحله",
    workflowStepKind: "خروجی",
    workflowStepModel: "مدل پیشنهادی",
    workflowStepPrompt: "درخواست این مرحله",
    workflowAddStep: "افزودن مرحله",
    workflowRemoveStep: "حذف مرحله",
    workflowSave: "ذخیرهٔ جریان‌کار",
    workflowCancel: "انصراف",
    workflowEdit: "ویرایش جریان‌کار",
    workflowPrivate: "خصوصی",
    workflowPublic: "عمومی",
    workflowPublish: "انتشار",
    workflowUnpublish: "خصوصی کردن",
    workflowOwn: "جریان‌کار تو",
    workflowSaving: "در حال ذخیره…",
    workflowChooseStep: "برای ادامه یک مرحله را انتخاب کن",
    workflowUseStep: "استفاده از این مرحله",
    workflowError: "ذخیرهٔ جریان‌کار انجام نشد.",
    workflowTitlePlaceholder: "مثلاً تصویر معرفی محصول",
    workflowDescriptionPlaceholder: "این جریان‌کار چه چیزی می‌سازد؟",
    workflowCategoryPlaceholder: "مثلاً بازاریابی",
    workflowPromptPlaceholder: "خروجی مورد انتظار این مرحله را توصیف کن…",
    workflowStepPlaceholder: "مثلاً طرح اولیه",
    sourceLinks: "منابع مرجع"
  }
} as const;
